/*
 * This file is generated by jOOQ.
 */
package io.metaloom.poc.db.jooq;


import io.metaloom.poc.db.jooq.tables.Group;
import io.metaloom.poc.db.jooq.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GROUP_NAME_IDX = Internal.createIndex(DSL.name("group_name_idx"), Group.GROUP, new OrderField[] { Group.GROUP.NAME }, true);
    public static final Index USER_USERNAME_IDX = Internal.createIndex(DSL.name("user_username_idx"), User.USER, new OrderField[] { User.USER.USERNAME }, true);
}
