/*
 * This file is generated by jOOQ.
 */
package io.metaloom.poc.db.jooq;


import io.metaloom.poc.db.jooq.tables.Group;
import io.metaloom.poc.db.jooq.tables.User;
import io.metaloom.poc.db.jooq.tables.UserGroup;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.group</code>.
     */
    public static final Group GROUP = Group.GROUP;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_group</code>.
     */
    public static final UserGroup USER_GROUP = UserGroup.USER_GROUP;
}
