/*
 * This file is generated by jOOQ.
 */
package io.metaloom.poc.db.jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.metaloom.poc.db.jooq.tables.Group;
import io.metaloom.poc.db.jooq.tables.interfaces.IGroup;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupRecord extends UpdatableRecordImpl<GroupRecord> implements VertxPojo, Record7<UUID, String, String, LocalDateTime, UUID, LocalDateTime, UUID>, IGroup {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.group.uuid</code>.
     */
    @Override
    public GroupRecord setUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.group.uuid</code>.
     */
    @Override
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.group.name</code>.
     */
    @Override
    public GroupRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.group.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.group.meta</code>.
     */
    @Override
    public GroupRecord setMeta(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.group.meta</code>.
     */
    @Override
    public String getMeta() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.group.created</code>.
     */
    @Override
    public GroupRecord setCreated(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.group.created</code>.
     */
    @Override
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.group.creator_uuid</code>.
     */
    @Override
    public GroupRecord setCreatorUuid(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.group.creator_uuid</code>.
     */
    @Override
    public UUID getCreatorUuid() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.group.edited</code>.
     */
    @Override
    public GroupRecord setEdited(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.group.edited</code>.
     */
    @Override
    public LocalDateTime getEdited() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.group.editor_uuid</code>.
     */
    @Override
    public GroupRecord setEditorUuid(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.group.editor_uuid</code>.
     */
    @Override
    public UUID getEditorUuid() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, String, String, LocalDateTime, UUID, LocalDateTime, UUID> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, String, String, LocalDateTime, UUID, LocalDateTime, UUID> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Group.GROUP.UUID;
    }

    @Override
    public Field<String> field2() {
        return Group.GROUP.NAME;
    }

    @Override
    public Field<String> field3() {
        return Group.GROUP.META;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Group.GROUP.CREATED;
    }

    @Override
    public Field<UUID> field5() {
        return Group.GROUP.CREATOR_UUID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Group.GROUP.EDITED;
    }

    @Override
    public Field<UUID> field7() {
        return Group.GROUP.EDITOR_UUID;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getMeta();
    }

    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    @Override
    public UUID component5() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime component6() {
        return getEdited();
    }

    @Override
    public UUID component7() {
        return getEditorUuid();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getMeta();
    }

    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    @Override
    public UUID value5() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime value6() {
        return getEdited();
    }

    @Override
    public UUID value7() {
        return getEditorUuid();
    }

    @Override
    public GroupRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public GroupRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GroupRecord value3(String value) {
        setMeta(value);
        return this;
    }

    @Override
    public GroupRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GroupRecord value5(UUID value) {
        setCreatorUuid(value);
        return this;
    }

    @Override
    public GroupRecord value6(LocalDateTime value) {
        setEdited(value);
        return this;
    }

    @Override
    public GroupRecord value7(UUID value) {
        setEditorUuid(value);
        return this;
    }

    @Override
    public GroupRecord values(UUID value1, String value2, String value3, LocalDateTime value4, UUID value5, LocalDateTime value6, UUID value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGroup from) {
        setUuid(from.getUuid());
        setName(from.getName());
        setMeta(from.getMeta());
        setCreated(from.getCreated());
        setCreatorUuid(from.getCreatorUuid());
        setEdited(from.getEdited());
        setEditorUuid(from.getEditorUuid());
    }

    @Override
    public <E extends IGroup> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupRecord
     */
    public GroupRecord() {
        super(Group.GROUP);
    }

    /**
     * Create a detached, initialised GroupRecord
     */
    public GroupRecord(UUID uuid, String name, String meta, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid) {
        super(Group.GROUP);

        setUuid(uuid);
        setName(name);
        setMeta(meta);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
    }

        public GroupRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
