/*
 * This file is generated by jOOQ.
 */
package io.metaloom.poc.db.jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.metaloom.poc.db.jooq.tables.interfaces.IGroup;

import java.time.LocalDateTime;
import java.util.UUID;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Group implements VertxPojo, IGroup {

    private static final long serialVersionUID = 1L;

    private UUID          uuid;
    private String        name;
    private String        meta;
    private LocalDateTime created;
    private UUID          creatorUuid;
    private LocalDateTime edited;
    private UUID          editorUuid;

    public Group() {}

    public Group(IGroup value) {
        this.uuid = value.getUuid();
        this.name = value.getName();
        this.meta = value.getMeta();
        this.created = value.getCreated();
        this.creatorUuid = value.getCreatorUuid();
        this.edited = value.getEdited();
        this.editorUuid = value.getEditorUuid();
    }

    public Group(
        UUID          uuid,
        String        name,
        String        meta,
        LocalDateTime created,
        UUID          creatorUuid,
        LocalDateTime edited,
        UUID          editorUuid
    ) {
        this.uuid = uuid;
        this.name = name;
        this.meta = meta;
        this.created = created;
        this.creatorUuid = creatorUuid;
        this.edited = edited;
        this.editorUuid = editorUuid;
    }

        public Group(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>public.group.uuid</code>.
     */
    @Override
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.group.uuid</code>.
     */
    @Override
    public Group setUuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>public.group.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.group.name</code>.
     */
    @Override
    public Group setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.group.meta</code>.
     */
    @Override
    public String getMeta() {
        return this.meta;
    }

    /**
     * Setter for <code>public.group.meta</code>.
     */
    @Override
    public Group setMeta(String meta) {
        this.meta = meta;
        return this;
    }

    /**
     * Getter for <code>public.group.created</code>.
     */
    @Override
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>public.group.created</code>.
     */
    @Override
    public Group setCreated(LocalDateTime created) {
        this.created = created;
        return this;
    }

    /**
     * Getter for <code>public.group.creator_uuid</code>.
     */
    @Override
    public UUID getCreatorUuid() {
        return this.creatorUuid;
    }

    /**
     * Setter for <code>public.group.creator_uuid</code>.
     */
    @Override
    public Group setCreatorUuid(UUID creatorUuid) {
        this.creatorUuid = creatorUuid;
        return this;
    }

    /**
     * Getter for <code>public.group.edited</code>.
     */
    @Override
    public LocalDateTime getEdited() {
        return this.edited;
    }

    /**
     * Setter for <code>public.group.edited</code>.
     */
    @Override
    public Group setEdited(LocalDateTime edited) {
        this.edited = edited;
        return this;
    }

    /**
     * Getter for <code>public.group.editor_uuid</code>.
     */
    @Override
    public UUID getEditorUuid() {
        return this.editorUuid;
    }

    /**
     * Setter for <code>public.group.editor_uuid</code>.
     */
    @Override
    public Group setEditorUuid(UUID editorUuid) {
        this.editorUuid = editorUuid;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Group (");

        sb.append(uuid);
        sb.append(", ").append(name);
        sb.append(", ").append(meta);
        sb.append(", ").append(created);
        sb.append(", ").append(creatorUuid);
        sb.append(", ").append(edited);
        sb.append(", ").append(editorUuid);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGroup from) {
        setUuid(from.getUuid());
        setName(from.getName());
        setMeta(from.getMeta());
        setCreated(from.getCreated());
        setCreatorUuid(from.getCreatorUuid());
        setEdited(from.getEdited());
        setEditorUuid(from.getEditorUuid());
    }

    @Override
    public <E extends IGroup> E into(E into) {
        into.from(this);
        return into;
    }
}
