/*
 * This file is generated by jOOQ.
 */
package io.metaloom.poc.db.jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.metaloom.poc.db.jooq.tables.interfaces.IUser;

import java.time.LocalDateTime;
import java.util.UUID;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements VertxPojo, IUser {

    private static final long serialVersionUID = 1L;

    private UUID          uuid;
    private String        username;
    private String        firstname;
    private String        lastname;
    private String        passwordhash;
    private String        email;
    private Boolean       enabled;
    private String        meta;
    private LocalDateTime created;
    private UUID          creatorUuid;
    private LocalDateTime edited;
    private UUID          editorUuid;

    public User() {}

    public User(IUser value) {
        this.uuid = value.getUuid();
        this.username = value.getUsername();
        this.firstname = value.getFirstname();
        this.lastname = value.getLastname();
        this.passwordhash = value.getPasswordhash();
        this.email = value.getEmail();
        this.enabled = value.getEnabled();
        this.meta = value.getMeta();
        this.created = value.getCreated();
        this.creatorUuid = value.getCreatorUuid();
        this.edited = value.getEdited();
        this.editorUuid = value.getEditorUuid();
    }

    public User(
        UUID          uuid,
        String        username,
        String        firstname,
        String        lastname,
        String        passwordhash,
        String        email,
        Boolean       enabled,
        String        meta,
        LocalDateTime created,
        UUID          creatorUuid,
        LocalDateTime edited,
        UUID          editorUuid
    ) {
        this.uuid = uuid;
        this.username = username;
        this.firstname = firstname;
        this.lastname = lastname;
        this.passwordhash = passwordhash;
        this.email = email;
        this.enabled = enabled;
        this.meta = meta;
        this.created = created;
        this.creatorUuid = creatorUuid;
        this.edited = edited;
        this.editorUuid = editorUuid;
    }

        public User(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>public.user.uuid</code>.
     */
    @Override
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.user.uuid</code>.
     */
    @Override
    public User setUuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>public.user.username</code>.
     */
    @Override
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.user.username</code>.
     */
    @Override
    public User setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>public.user.firstname</code>.
     */
    @Override
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.user.firstname</code>.
     */
    @Override
    public User setFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }

    /**
     * Getter for <code>public.user.lastname</code>.
     */
    @Override
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.user.lastname</code>.
     */
    @Override
    public User setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    /**
     * Getter for <code>public.user.passwordhash</code>.
     */
    @Override
    public String getPasswordhash() {
        return this.passwordhash;
    }

    /**
     * Setter for <code>public.user.passwordhash</code>.
     */
    @Override
    public User setPasswordhash(String passwordhash) {
        this.passwordhash = passwordhash;
        return this;
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    @Override
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    @Override
    public User setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.user.enabled</code>.
     */
    @Override
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>public.user.enabled</code>.
     */
    @Override
    public User setEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Getter for <code>public.user.meta</code>.
     */
    @Override
    public String getMeta() {
        return this.meta;
    }

    /**
     * Setter for <code>public.user.meta</code>.
     */
    @Override
    public User setMeta(String meta) {
        this.meta = meta;
        return this;
    }

    /**
     * Getter for <code>public.user.created</code>.
     */
    @Override
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>public.user.created</code>.
     */
    @Override
    public User setCreated(LocalDateTime created) {
        this.created = created;
        return this;
    }

    /**
     * Getter for <code>public.user.creator_uuid</code>.
     */
    @Override
    public UUID getCreatorUuid() {
        return this.creatorUuid;
    }

    /**
     * Setter for <code>public.user.creator_uuid</code>.
     */
    @Override
    public User setCreatorUuid(UUID creatorUuid) {
        this.creatorUuid = creatorUuid;
        return this;
    }

    /**
     * Getter for <code>public.user.edited</code>.
     */
    @Override
    public LocalDateTime getEdited() {
        return this.edited;
    }

    /**
     * Setter for <code>public.user.edited</code>.
     */
    @Override
    public User setEdited(LocalDateTime edited) {
        this.edited = edited;
        return this;
    }

    /**
     * Getter for <code>public.user.editor_uuid</code>.
     */
    @Override
    public UUID getEditorUuid() {
        return this.editorUuid;
    }

    /**
     * Setter for <code>public.user.editor_uuid</code>.
     */
    @Override
    public User setEditorUuid(UUID editorUuid) {
        this.editorUuid = editorUuid;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(uuid);
        sb.append(", ").append(username);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(passwordhash);
        sb.append(", ").append(email);
        sb.append(", ").append(enabled);
        sb.append(", ").append(meta);
        sb.append(", ").append(created);
        sb.append(", ").append(creatorUuid);
        sb.append(", ").append(edited);
        sb.append(", ").append(editorUuid);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser from) {
        setUuid(from.getUuid());
        setUsername(from.getUsername());
        setFirstname(from.getFirstname());
        setLastname(from.getLastname());
        setPasswordhash(from.getPasswordhash());
        setEmail(from.getEmail());
        setEnabled(from.getEnabled());
        setMeta(from.getMeta());
        setCreated(from.getCreated());
        setCreatorUuid(from.getCreatorUuid());
        setEdited(from.getEdited());
        setEditorUuid(from.getEditorUuid());
    }

    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }
}
